#!/bin/bash
echo $0 | logger
echo `pwd`  | logger

if test -z "$JMARECEIPT_ENV" ; then
    JMARECEIPT_ENV="/etc/jma-receipt/jma-receipt.env"
fi
if ! test -f "$JMARECEIPT_ENV"; then
    exit 0
fi

. $JMARECEIPT_ENV

umask 022

# program option set
bash ${SITESRCDIR}/scripts/prgoption/prgoption.sh
rm -r ${SITESRCDIR}/scripts/prgoption
echo -n "prgoption......done" | logger

PATH=.:${PATH}

# compile COBOL programs
COBMEM=`module CBL`
for f in ${COBMEM}; do
  if test "x`echo -n $f | grep 'CBL$'`" != "x"; then
    m=`echo $f | sed 's/CBL$/so/'`
    echo -n "Building ${m}..." | logger
    ${COBOL} ${COBOLFLAGS} -o ${SITELIBDIR}/${m} \
         -I ${PATCHCOPYDIR} \
         -I ${COPYDIR} \
         -I ${SITESRCDIR}/cobol/copy \
        ${SITESRCDIR}/cobol/${f}
  fi
done

# copy scripts file
SCRIPTMEM=`module scripts`
for f in ${SCRIPTMEM}; do 
  if test -f "${SITESRCDIR}/${f}"; then
    echo -n "Copying ${SITESRCDIR}/${f}..." | logger
    sed -e 's,\@jma-receipt-env\@,/etc/jma-receipt/jma-receipt.env,g' \
        < "${SITESRCDIR}/${f}" > "${SITEDIR}/${f}"
	chmod +x "${SITEDIR}/${f}"
  fi
done
echo "done"

# copy lddef file
LDDEFMEM=`module lddef`
for f in ${LDDEFMEM}; do 
  if test -f "${SITESRCDIR}/${f}"; then
    echo -n "Copying ${SITESRCDIR}/${f}..." | logger
    $CPP -I"${LDDEFDIR}" -x c "${SITESRCDIR}/${f}" > "${SITEDIR}/${f}"
  fi
done
echo "done"

# copy data files
for d in data doc form init record screen ; do
  m=`module ${d}`
  for f in ${m}; do 
    if test -f "${SITESRCDIR}/${f}"; then
      echo -n "Copying ${SITESRCDIR}/${f}..." | logger
      cp -p "${SITESRCDIR}/${f}" "${SITEDIR}/${d}"
    fi
  done
done
echo "done"

#modify kentan.inc
if test -f ./kentan.inc; then
  PREF=`cat ./kentan.inc`
  echo -n "Modifying kentan.inc files... ${PREF}" | logger
  cp ${SYSCONFDIR}/kentan.inc /tmp/kentan.inc.bak
  sed "/${PREF}/d" /tmp/kentan.inc.bak > ${SYSCONFDIR}/kentan.inc
  rm -rf /tmp/kentan.inc.bak
  echo -e "\t${PREF};" >> ${SYSCONFDIR}/kentan.inc
  echo "done"
fi
