#!/bin/bash
echo $0 | logger
echo `pwd`  | logger

#--# if test -z "$JMARECEIPT_ENV" ; then
#--#     JMARECEIPT_ENV="/etc/jma-receipt/jma-receipt.env"
#--# fi
#--# if ! test -f "$JMARECEIPT_ENV" ; then
#--#     exit 0
#--# fi
#--# 
#--# . $JMARECEIPT_ENV

#-- postlink へ移行 ここから
#--# if ! test -d ${SITESRCDIR}/scripts/prgoption ; then
#--#     mkdir -m 775 ${SITESRCDIR}/scripts/prgoption
#--# fi
#--# 
#--# if ! test -d ${SITESRCDIR}/scripts/syskanri ; then
#--#     mkdir -m 775 ${SITESRCDIR}/scripts/syskanri
#--# fi
#-- postlink へ移行 ここまで

#-- preinst へ移行 ここから
#--# #rm
#--# echo -n "rm start" | logger
#--# for d in cobol data doc form lddef init record screen scripts; do
#--#   m='module ${d}'
#--#   for f in ${m}; do
#--#     if test -f "${SITESRCDIR}/${f}" ; then
#--#        echo -n "rm ${SITESRCDIR}/${f}..." | logger
#--#        rm  ${SITESRCDIR}/${f}
#--#     fi
#--#   done
#--# done
#-- preinst へ移行 ここまで
